### ISSUE TITLE
How to setup and where to launch this?

### ISSUE THREAD

**Issue by scheung38** [madflojo/automatron#115]
```
$ sudo docker run -d --link redis:redis -p 8000:8000 -p 9000:9000 -v /path/to/config:/config --restart=always --name automatron madflojo/automatron

$ command not found 

```
Must I first clone the project first?

As I cloned project and tried : 

```
$ sudo docker run -d --link redis:redis -p 8000:8000 -p 9000:9000 -v /$HOME/automatron/config:/config --restart=always --name automatron madflojo/automatron
-bash: 
$: command not found
```

EDIT:

Just need to 

```
# apt-get update
# apt-get install sudo
```

But

```
# sudo apt-get install python2.7 python-dev \
                       python-pip redis-server \
                       nmap git libffi-dev \
                       build-essential libssl-dev      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libs
```

Also do I open within the docker container or host 

docker inspect --format '{{ .NetworkSettings.IPAddress }}' 5d587aeb87ed
172.17.0.2

`
http://<host ip>:8080
`
`
http://172.17.0.2:8080
`

not sure how to host host ip as this can't connect and show dashboard?

**Comment by madflojo** [comment]
@scheung38 I made some documentation changes in #116 do these help clarify things a bit?

**Comment by madflojo** [comment]
Closing this for now, but feel free to reopen and comment if you have questions still.
